import React, { useState, useRef, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { Activity, ShieldAlert, HeartPulse, User, Calendar, Send, AlertCircle, TrendingUp, TrendingDown, Beaker, MessageCircle } from 'lucide-react';

const getStatusColor = (status) => {
  switch(status) {
    case 'Normal': return 'var(--status-normal)';
    case 'Low': return 'var(--status-low)';
    case 'High': return 'var(--status-high)';
    case 'Critical': return 'var(--status-critical)';
    default: return 'var(--text-secondary)';
  }
};

const getStatusClass = (status) => {
  switch(status) {
    case 'Normal': return 'status-normal';
    case 'Low': return 'status-low';
    case 'High': return 'status-high';
    case 'Critical': return 'status-critical';
    default: return '';
  }
};

// Gauge component for visualizing biomarker values
function BiomarkerGauge({ value, min, max, status }) {
  const rangeSpan = max - min;
  const gaugeMin = min - rangeSpan * 0.5;
  const gaugeMax = max + rangeSpan * 0.5;
  const totalSpan = gaugeMax - gaugeMin;

  const normalStart = ((min - gaugeMin) / totalSpan) * 100;
  const normalWidth = ((max - min) / totalSpan) * 100;
  const markerPos = Math.max(0, Math.min(100, ((value - gaugeMin) / totalSpan) * 100));

  return (
    <div className="gauge-container">
      <div className="gauge-track">
        <div className="gauge-range" style={{ left: `${normalStart}%`, width: `${normalWidth}%` }} />
        <div className="gauge-marker" style={{ left: `${markerPos}%`, background: getStatusColor(status) }} />
      </div>
      <div className="gauge-labels">
        <span>{gaugeMin.toFixed(1)}</span>
        <span style={{ color: 'var(--status-normal)', fontWeight: 600 }}>{min} - {max}</span>
        <span>{gaugeMax.toFixed(1)}</span>
      </div>
    </div>
  );
}

// Animated counter
function AnimatedCount({ value, duration = 1000 }) {
  const [display, setDisplay] = useState(0);
  useEffect(() => {
    let start = 0;
    const step = value / (duration / 16);
    const timer = setInterval(() => {
      start += step;
      if (start >= value) { setDisplay(value); clearInterval(timer); }
      else setDisplay(Math.floor(start));
    }, 16);
    return () => clearInterval(timer);
  }, [value, duration]);
  return <span>{display}</span>;
}

export default function DashboardView({ reportData, onReset }) {
  const { lab_report: labReport, analysis, id: reportId } = reportData;
  const [chatMessage, setChatMessage] = useState('');
  const [chatHistory, setChatHistory] = useState([
    { role: 'assistant', content: 'Hello! I\'m MedScan AI. Ask me any follow-up questions about your lab report — I\'ll explain results, causes, or lifestyle tips.' }
  ]);
  const [isTyping, setIsTyping] = useState(false);
  const chatEndRef = useRef(null);

  const abnormalTests = analysis.abnormal_findings || [];
  const normalTests = labReport.test_results.filter(t => t.status === 'Normal');
  const totalTests = labReport.test_results.length;

  // Auto-scroll chat
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatHistory, isTyping]);

  const handleChatSubmit = async (e) => {
    e.preventDefault();
    if (!chatMessage.trim()) return;

    const userMsg = chatMessage;
    setChatMessage('');
    setChatHistory(prev => [...prev, { role: 'user', content: userMsg }]);
    setIsTyping(true);

    try {
      const response = await fetch('http://localhost:8000/api/v1/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ report_id: reportId, message: userMsg, history: chatHistory })
      });
      
      const data = await response.json();
      setChatHistory(prev => [...prev, { role: 'assistant', content: data.response }]);
    } catch (err) {
      setChatHistory(prev => [...prev, { role: 'assistant', content: "Sorry, I couldn't reach the server. Please try again." }]);
    } finally {
      setIsTyping(false);
    }
  };

  return (
    <div className="container animate-fade-in">
      {/* Header */}
      <div className="flex-between" style={{ marginBottom: '32px' }}>
        <div>
          <h1 style={{ fontSize: '2rem', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <Activity color="var(--accent-color)" size={30} />
            Diagnostic <span className="text-gradient">Analysis</span>
          </h1>
          <p className="text-small">Generated by MedScan AI Hybrid RAG Engine</p>
        </div>
        <button className="btn-ghost" onClick={onReset}>Upload New Report</button>
      </div>

      {/* Stats Row */}
      <div className="stats-row animate-fade-in-up">
        <div className="stat-card">
          <div className="stat-value" style={{ color: 'var(--accent-color)' }}>
            <AnimatedCount value={totalTests} />
          </div>
          <div className="stat-label">Tests Extracted</div>
        </div>
        <div className="stat-card">
          <div className="stat-value" style={{ color: 'var(--status-high)' }}>
            <AnimatedCount value={abnormalTests.length} />
          </div>
          <div className="stat-label">Abnormal Findings</div>
        </div>
        <div className="stat-card">
          <div className="stat-value" style={{ color: 'var(--status-normal)' }}>
            <AnimatedCount value={normalTests.length} />
          </div>
          <div className="stat-label">Normal Results</div>
        </div>
      </div>

      <div className="dashboard-grid">
        
        {/* LEFT SIDEBAR */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          
          {/* Patient Info */}
          <div className="glass-card animate-fade-in-up" style={{ padding: '24px' }}>
            <h3 style={{ borderBottom: '1px solid var(--glass-border)', paddingBottom: '14px', marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.95rem' }}>
              <User size={16} color="var(--accent-color)"/> Patient Info
            </h3>
            <div style={{ display: 'grid', gap: '12px' }}>
              <div className="flex-between">
                <span className="text-small">Name</span>
                <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>{labReport.patient.name || 'Unknown'}</span>
              </div>
              <div className="flex-between">
                <span className="text-small">Age / Gender</span>
                <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>{labReport.patient.age || '-'} / {labReport.patient.gender || '-'}</span>
              </div>
              <div className="flex-between">
                <span className="text-small">Report Date</span>
                <span style={{ fontWeight: 600, fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap:'6px' }}>
                  <Calendar size={13}/> {labReport.report_date || 'Unknown'}
                </span>
              </div>
            </div>
          </div>

          {/* Clinical Summary */}
          <div className="glass-card animate-fade-in-up animate-delay-1" style={{ padding: '24px', position: 'relative', overflow: 'hidden' }}>
            <div style={{ position: 'absolute', top: 0, left: 0, width: '3px', height: '100%', background: 'linear-gradient(to bottom, #60A5FA, #A78BFA)' }}></div>
            <h3 style={{ marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.95rem' }}>
              <HeartPulse size={16} color="var(--accent-color)"/> Clinical Summary
            </h3>
            <p style={{ fontSize: '0.9rem', lineHeight: '1.75' }}>
              {analysis.overall_summary}
            </p>
          </div>

          {/* Questions for Doctor */}
          {analysis.questions_for_doctor && analysis.questions_for_doctor.length > 0 && (
            <div className="glass-card animate-fade-in-up animate-delay-2" style={{ padding: '24px' }}>
              <h3 style={{ marginBottom: '14px', color: '#F59E0B', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.95rem' }}>
                <AlertCircle size={16}/> Questions for your Doctor
              </h3>
              <ul style={{ listStyleType: 'disc', fontSize: '0.88rem', display: 'flex', flexDirection: 'column', gap: '10px', lineHeight: '1.6' }}>
                {analysis.questions_for_doctor.map((q, i) => <li key={i}>{q}</li>)}
              </ul>
            </div>
          )}
          
          {/* Chat */}
          <div className="glass-card chat-container animate-fade-in-up animate-delay-3">
            <div className="chat-header">
              <MessageCircle size={16} color="var(--accent-color)"/>
              <h3>MedScan AI Chat</h3>
              <div className="chat-online-dot" style={{ marginLeft: 'auto' }}></div>
            </div>
            
            <div className="chat-messages">
              {chatHistory.map((msg, i) => (
                <div key={i} className={`chat-bubble ${msg.role}`}>
                  {msg.role === 'assistant' ? (
                    <ReactMarkdown>{msg.content}</ReactMarkdown>
                  ) : (
                    msg.content
                  )}
                </div>
              ))}
              {isTyping && (
                <div className="typing-indicator">
                  <div className="typing-dot"></div>
                  <div className="typing-dot"></div>
                  <div className="typing-dot"></div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>
            
            <form onSubmit={handleChatSubmit} className="chat-input-area">
              <input 
                type="text" 
                value={chatMessage}
                onChange={e => setChatMessage(e.target.value)}
                placeholder="Ask about this report..." 
                disabled={isTyping}
                className="chat-input"
              />
              <button type="submit" disabled={isTyping || !chatMessage.trim()} className="chat-send-btn">
                <Send size={16} color="white" />
              </button>
            </form>
          </div>

        </div>

        {/* RIGHT MAIN AREA */}
        <div>
          <h2 style={{ marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '10px', fontSize: '1.3rem' }}>
            <ShieldAlert color="#EF4444" size={22}/>
            Abnormal Findings
            <span style={{ fontSize: '0.85rem', background: 'rgba(239, 68, 68, 0.15)', padding:'4px 14px', borderRadius:'20px', marginLeft:'8px', fontWeight: 600 }}>
              {abnormalTests.length}
            </span>
          </h2>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {abnormalTests.length === 0 ? (
              <div className="glass-panel" style={{ padding: '48px', textAlign: 'center' }}>
                <h3 style={{ color: 'var(--status-normal)', marginBottom: '8px' }}>No Abnormal Findings!</h3>
                <p>All extracted test results appear to be within the normal reference ranges.</p>
              </div>
            ) : (
              abnormalTests.map((finding, idx) => (
                <div key={idx} className="glass-card biomarker-row animate-fade-in-up" style={{ animationDelay: `${idx * 0.1}s` }}>
                  <div className="biomarker-header">
                    <div>
                      <div className="text-small" style={{ marginBottom: '4px', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>BIOMARKER</div>
                      <div style={{ fontWeight: 700, fontSize: '1.05rem' }}>{finding.test_name}</div>
                    </div>
                    
                    <div>
                      <div className="text-small" style={{ marginBottom: '4px', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>RESULT</div>
                      <div style={{ fontWeight: 800, fontSize: '1.15rem', color: getStatusColor(finding.status), display: 'flex', alignItems: 'center', gap: '6px' }}>
                        {finding.status === 'High' ? <TrendingUp size={16}/> : <TrendingDown size={16}/>}
                        {finding.patient_value} <span style={{ fontSize: '0.8rem', fontWeight: 400, color: 'var(--text-secondary)' }}>{finding.unit}</span>
                      </div>
                    </div>

                    <div style={{ textAlign: 'right' }}>
                      <div className="text-small" style={{ marginBottom: '6px', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>STATUS</div>
                      <span className={`status-badge ${getStatusClass(finding.status)}`}>
                        {finding.status}
                      </span>
                    </div>
                  </div>

                  {/* Gauge Bar */}
                  {finding.patient_value != null && (
                    <BiomarkerGauge 
                      value={finding.patient_value}
                      min={finding.reference_min || finding.patient_value * 0.7} 
                      max={finding.reference_max || finding.patient_value * 1.3}
                      status={finding.status}
                    />
                  )}

                  <div className="biomarker-details">
                    <div className="insight-card meaning">
                      <div className="insight-title">
                        <Activity size={13} /> Medical Meaning
                      </div>
                      <p style={{ fontSize: '0.88rem', lineHeight: '1.65', color: 'var(--text-primary)' }}>{finding.interpretation}</p>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                      {finding.possible_causes && finding.possible_causes.length > 0 && (
                        <div className="insight-card causes">
                          <div className="insight-title">
                            <AlertCircle size={13} /> Possible Causes
                          </div>
                          <ul style={{ fontSize: '0.85rem' }}>
                            {finding.possible_causes.map((c, i) => <li key={i}>{c}</li>)}
                          </ul>
                        </div>
                      )}

                      {finding.lifestyle_tips && finding.lifestyle_tips.length > 0 && (
                        <div className="insight-card tips">
                          <div className="insight-title">
                            <HeartPulse size={13} /> Lifestyle Tips
                          </div>
                          <ul style={{ fontSize: '0.85rem' }}>
                            {finding.lifestyle_tips.map((t, i) => <li key={i}>{t}</li>)}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
          
          {/* Normal Results */}
          {normalTests.length > 0 && (
            <div style={{ marginTop: '40px' }} className="animate-fade-in-up">
              <h3 style={{ marginBottom: '16px', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '1rem' }}>
                <Beaker size={16}/> Normal Results ({normalTests.length})
              </h3>
              <div className="glass-card" style={{ padding: '16px', display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                {normalTests.map((t, i) => (
                  <span key={i} className="normal-chip">
                    {t.test_name}: <strong style={{ color: 'var(--status-normal)' }}>{t.value} {t.unit}</strong>
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
